### ISSUE TITLE
[feature] pokemons sightings notifications

### ISSUE THREAD

**Issue by Xelwon** [chuparCh0pper/PoGoIV_xposed#13]
The idea was.
Send a notification with the list of pokemon in sighings view with the coordinates of where are they. 
And resend it every given time (or if possible when the list change)
And, if possible too,  when you touch in the notification open a google maps with the points of where are :D

**Comment by igoticecream** [comment]
Sighings pokemons (aka nearby pokemons on the protos) doesnt have coordinates

**Comment by pperle** [comment]
@igoticecream is right "nearby_pokemons" do not have a latitude & longitude.

``` json
  "nearby_pokemons": [
      {
       "encounter_id": 0086931240006536365, 
       "pokemon_id": 60
      }, 
      {
       "encounter_id": 00421431047592950000, 
       "pokemon_id": 21
      }, 
      {
       "encounter_id": 8780494938259158109, 
       "pokemon_id": 98
      }
     ], 
```

from https://www.reddit.com/r/pokemongodev/comments/4xauk4/understanding_get_map_objects_response/ (changed x to 0)
