### ISSUE TITLE
Remove multidex

### ISSUE THREAD

**Issue by igoticecream** [chuparCh0pper/PoGoIV_xposed#14]
Hello, this is not an issue, but a recomendation.

protobuf-java has a heavy method counts and it's recommended for android projects to use protobuf-lite instead:

```
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }
    plugins {
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite { }
            }
        }
    }
}

dependencies {
    compile 'com.google.protobuf:protobuf-lite:3.0.0'
}
```

Then you can drop support for multidex since is no longer needed

**Comment by pperle** [comment]
Is there a way to compile POGOProtos as protobuf-lite?

**Comment by igoticecream** [comment]
I will make a pull request. The final apk should be 800kbs tops and without multidex

**Comment by pperle** [comment]
https://github.com/chuparCh0pper/PoGoIV_xposed/commit/914f845da0fcd12c15898b530b11de6ef2f03ba4
