### ISSUE TITLE
Heads Up Notification Issues

### ISSUE THREAD

**Issue by ghost** [chuparCh0pper/PoGoIV_xposed#15]
Hello chuparCh0pper! nicely done really, but there are few issues happening exclusively to a TouchWiz 6.0.1 user.
Issue regarding pulling down the Heads Up notification as it doesn't expand it instead it pulls down the notifications bar.
Issue if the Pokemon name is long it would kinda hide extra info like level and sometimes even CP, I would suggest either resizing the writing or including the level in second row, as you like.
P.S. Would be great if we had the ability to customize the notification but that could require alot of work so I'm not pushing it further.

**Comment by pperle** [comment]
> Issue regarding pulling down the Heads Up notification as it doesn't expand it instead it pulls down the notifications bar.

This sometimes happens to me as well. Try to get rid of any other notification, so it is easier to grab the one you want to extend.

**Comment by ghost** [comment]
@chuparCh0pper I still can't seem to get it expand. Any ideas?

**Comment by pperle** [comment]
Could you please post a screenshot.

**Comment by chuman72486** [comment]
Attached is an example of the toast when a Pokémon would be about to break
out of the Pokéball.

**Comment by ghost** [comment]
The first issue is full info is not shown due to lack of space.

When I try to pull this notification down to expand it! this what happens:

Pulls down the hole notification bar along with all notifications in case there where any.

**Comment by pperle** [comment]
The title being too long for you is annoying, I can see that. This issue has been addressed in 2014 (https://code.google.com/p/android/issues/detail?id=82065) but still Google didn’t fix it. Well I guess the best thing would be the ability to customize the notification.
The pull down is normal after the headup notification disappeared, that’s how android handles this.

**Comment by ghost** [comment]
> Well I guess the best thing would be the ability to customize the notification.

That's actually a great idea!

> The pull down is normal after the headup notification disappeared, that’s how android handles this.

TouchWiz handles it differently from AOSP! At a glance looking at PoGoIV Xposed GIF! I thought it wasn't showing the panel! but I see it clearly now!

Thank you @chuparCh0pper for replying!
