### ISSUE TITLE
Scrolling the gym info notification

### ISSUE THREAD

**Issue by MrZoolook** [chuparCh0pper/PoGoIV_xposed#29]
When there are more than 2 Pokémon in a gym, in the notification with the gym info, scrolling down past the first 2 will only display the first 3 lines of info on the 3rd 'mon instead of the full 4 lines.

**Comment by pperle** [comment]
fixed https://github.com/chuparCh0pper/PoGoIV_xposed/commit/2f20def1380914c27b4d20a08b392be8f9e8ccae will push to xposed repo in the next few days
