### ISSUE TITLE
[v1.16] - Delayed Encounter Notifications

### ISSUE THREAD

**Issue by likebutta222** [chuparCh0pper/PoGoIV_xposed#31]
As a preface, I've tried restarting my phone, restarting the module and starting the module before Pokemon Go is started.  The encounter notification seems to come delayed (I'm trying to see if there is an exact timing or if its just random), normally coming a couple minutes after the encounter.  At one location with multiple lures, nothing showed up until multiple encounter notifications popped and override the last, some time after the captures had occurred.

All other features appear to work fine and on time (re: Catch toasts, inventory toasts)

If there is anything else I can do to help test or narrow it down, let me know.

Running:
Nexus 6P
Stock Android 6.0.1 + Root/Suhide + Systemless Xposed v86.2

For reference purposes:  I've tried the Snorlax module and the notifications there seem to function normally.

**Comment by pperle** [comment]
Snorlax and this module handle notification differently.
Snorlax uses PoGo to post notifications, this module makes PoGo send a Broadcast which is received by PoGoIV. Try to open PoGoIV before starting PoGo.
