### ISSUE TITLE
Gyms showing 'Error' on first encounter.

### ISSUE THREAD

**Issue by FakeKitten** [chuparCh0pper/PoGoIV_xposed#32]
Since the update for 0.39 I've been having a weird issue where trying to fight a gym will always show "Error" or "Network Error" the first time I try to fight it and will only work once I restart pokemon go and after that I can fight that gym. Oddly restarting the app before encountering a new gym doesn't help as the error will still show, the only way to  fight a gym is to try once, see the "Error" then restart.

After disabling this xposed module and restarting my phone the issue seems to have cleared. 
~~The only thing I haven't tested is if the problem is due to a conflict with snorlax module.~~

Edit: I've also tested disabling all other pokemon go related modules and only keeping this one active. The gym error bug still persists.

Also the "Enable Module" switch is currently useless. The module stays active no matter of the state of the switch.

One last, somewhat unrelated thing; what the fuck does the % number shown when a pokemon escapes or flees actually mean?

**Comment by pperle** [comment]
I could recreate the issue, I will look into it.
The % shows the MissPercent https://github.com/Armax/Pokemon-GO-node-api/blob/master/pokemon.proto#L960.

**Comment by danizwam** [comment]
Any progress? ;)

**Comment by pperle** [comment]
Hey @danizwam,
Since the latest update to SafetyNet I cannot start Pokémon Go.
When there is a "good way" to bypass SafetyNet that does not force me to flash different xposed/su types every week I might start playing Pokémon Go again and and continue the development of this module.

I am very sorry.

**Comment by danizwam** [comment]
@chuparCh0pper 

It's a combination of some SU, Xposed and Hide-Tools ;)

-SuperSU 2.78 SR1
- Xposed 82.2 (Special Version, works without Magisk)
- SuHide 0.55
- RootSwitch 1.24 

You won't have root while playing PoGo, but Xposed works fine.

To bypass SafetyNet, you have to toggle ALL SU DAEMONS in RootSwitch, bevor disabling root.

This setups works now for about two weeks. The latest SafetyNet Update forced me to disable all SU Daemons, but that's OK for me. 

Magisk V7 and MagiskHide is out too, but i haven't tried them.

Follow these steps:

https://www.reddit.com/r/pokemongodev/comments/58gnq3/root_bypass_the_new_update_leads_repost/

Edit:

My Setup: OnePlus One on CM13 by Sultan

Edit #2:

You'll find Xposed 82.2 in this Thread: http://forum.xda-developers.com/apps/supersu/suhide-t3450396

**Comment by pperle** [comment]
Thank you @danizwam for the detailed description.
I had to swap from cm14 back to cm13 as there is no xposed for SDK25 yet. After installing SuperSU 2.78 SR1 as systemless I also had to delete /system/bin/su and /system/xbin/su before flashing SuHide 0.55

Well anyways I think I fixed the bug, please update to v.1.6.1

EDIT: where we go again.. https://www.reddit.com/r/pokemongodev/comments/59bdd0/new_safetynet_update/
