### ISSUE TITLE
0.59.1 breaks module

### ISSUE THREAD

**Issue by Mike-Ferretti** [chuparCh0pper/PoGoIV_xposed#33]
The newest update of PoGo (0.59.1) completely breaks the module. It no longer pops up when you encounter a wild Pokemon and doesn't say whether or not the catch is a success or not.

**Comment by pperle** [comment]
@iTzFeRReTTi As I stopped playing pokemon go I stopped the development of this module. The most up to date version is https://github.com/alucas/Snorlax . Saying this Snorlax also does not work with 0.59.1 (my guess is that the protos need to be updated. @alucas is already working on this https://github.com/alucas/POGOProtos/tree/v2.8.0) https://github.com/alucas/Snorlax/issues/54

**Comment by Mike-Ferretti** [comment]
Okay, thank you very much! :)
