### ISSUE TITLE
[Feature request] berry catch rate modifier

### ISSUE THREAD

**Issue by shark0der** [chuparCh0pper/PoGoIV_xposed#9]
First of all, awesome piece of work! Thank you!
I've stumbled across this https://pokemongo.gamepress.gg/catch-mechanics and was thinking it would be a nice idea to integrate some of these in the app, for example rate when using berry modifier in notification, maybe there's more useful info.

**Comment by pperle** [comment]
Do you mean like this:

```
CaptureProbability:
Pokéball: 35% (with Razzberry 52.5%)
```

Or do you want to update the info in the notification after a razzberry has been thrown?

**Comment by shark0der** [comment]
I think the provided example provides enough info so you won't have to sniff the razzbery throwing.
Another idea would be to show rate per throw type, but as I can see that info is an assumption, nothing for sure yet.

Another idea that would probably go into a new feature request would be Pokémon suggestions when entering a gym (i.e. suggest best Pokémon trainer has to be used against the entered gym). What do you think?

**Comment by pperle** [comment]
added berry catch rate https://github.com/chuparCh0pper/PoGoIV_xposed/commit/857cc35f8c4bca90e5a24aab2dd71724cf36a9cc

> when entering a gym (i.e. suggest best Pokémon trainer has to be used against the entered gym).

I think this would exceed the scope of this module. But it sounds like agood idea for a new module :wink:

**Comment by shark0der** [comment]
Wow, that was fast! Thanks!  👍
